# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3      
    - uses: conda-incubator/setup-miniconda@v2
      with:
        architecture: x64      
        miniconda-version: "latest"
        channels: conda, conda-forge
        use-only-tar-bz2: true 
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies  
      run: |
        #echo ${{ github.workspace }}
        sudo apt-get update
        sudo apt-get install libglu1-mesa libxrender1 libxcursor1 libxft2 libxinerama1 ffmpeg libsm6 libxext6
        echo ${{ github.workspace }}        
        conda install -c conda-forge -y petsc4py

        python -m pip install --upgrade pip
        python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt
        python -m pip install pytest==8.2.2
    - name: Test with pytest
      run: |
        python -m pytest
