# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: ["main" , "develop"]
  pull_request:
    branches: ["main" , "develop"]

jobs:
  build:
    name: Check installation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    
    - uses: actions/checkout@v3      
    - uses: conda-incubator/setup-miniconda@v2
      with:
        architecture: x64      
        miniconda-version: "latest"
        channels: conda, conda-forge
        use-only-tar-bz2: true 
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies  
      run: |        
        sudo apt-get install libglu1-mesa libxrender1 libxcursor1 libxft2 libxinerama1 ffmpeg libsm6 libxext6
        sudo apt-get install libglu1
        conda install -c conda-forge petsc
        conda install -c conda-forge petsc4py
        
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt

    - name: Install nfempy
      run: |
        python -m pip install .
        python -m pip freeze   

    - name: Test nfempy geometry
      run: |
        python -m pytest tests/test_geometry

    - name: Test nfempy meshing
      run: |
        python -m pytest tests/test_meshing   
