# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: ["main" , "develop"]
  pull_request:
    branches: ["main" , "develop"]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Check installation
    - uses: actions/checkout@v3      
    - uses: conda-incubator/setup-miniconda@v2
      with:
        architecture: x64      
        miniconda-version: "latest"
        channels: conda, conda-forge
        use-only-tar-bz2: true 
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies  
      run: |
        echo ${{ github.workspace }}
        sudo apt-get install libglu1-mesa libxrender1 libxcursor1 libxft2 libxinerama1 ffmpeg libsm6 libxext6
        # conda init bash
        # conda create --yes --name nfempy
        # ls
        # conda activate nfempy || true        
        echo ${{ github.workspace }}
        # # install a message passing interface and mpi4py
        # sudo apt-get install libopenmpi-dev  # alt.: conda install -c conda-forge openmpi
        # pip install --user mpi4py  # alt.: conda install -c anaconda mpi4py
        
        # # install petsc and and petsc4py
        # conda install -c conda-forge petsc
        # conda install -c conda-forge petsc4py
        
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt
        # python -m pip install --upgrade cython
        # python -m pip install mpi4py petsc #petsc4py
        conda install -c conda-forge petsc
        conda install -c conda-forge petsc4py

    # - name: Test with pytest
    #   run: |
    #     python -m pytest
